
        
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  codeql-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ['javascript']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        
      - name: Autobuild CodeQL database
        uses: github/codeql-action/autobuild@v1
        
      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v1

  deploy-to-azure-app-service:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      - name : Login via Azure CLI 
        uses : azure/login@v1 
        with :
          creds : ${{ secrets.AZURE_CREDENTIALS }}
      
      - name : Set up Azure WebApp 
        uses : azure/webapps-deploy@v2 
        with :
          app-name : <your-app-name>
          slot-name : <optional-slot-name>
          publish-profile : ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

        