
        
name: Python Flask CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  build-and-deploy-docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image to DockerHub
        run: |
          docker build . -t your-dockerhub-username/python-flask-app:$GITHUB_SHA
          docker push your-dockerhub-username/python-flask-app:$GITHUB_SHA
      
  deploy-to-gke:
    needs : build-and-deploy-docker 
    runs-on : ubuntu-latest 
    steps :
     # Configure Google Cloud SDK 
     # Authenticate with Google Cloud using the provided service account key 
     # Set the default project and zone for GKE cluster 
     # Update kubectl configuration to use the provided GKE cluster 

     # Deploy the Docker image to the Kubernetes cluster on GKE 


        